
   import { create } from 'zustand';

// Define a function to get the list of Algerian wilayas
const getAlgerianWilayas = () => [
  'Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouira', 'Tamanrasset', 'Tébessa', 'Tlemcen', 'Tiaret', 'Tizi Ouzou', 'Algiers', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda', 'Sidi Bel Abbès', 'Annaba', 'Guelma', 'Constantine', 'Médéa', 'Mostaganem', 'M\'Sila', 'Mascara', 'Ouargla', 'Oran', 'El Bayadh', 'Illizi', 'Bordj Bou Arréridj', 'Boumerdès', 'El Tarf', 'Tindouf', 'Tissemsilt', 'El Oued', 'Khenchela', 'Souk Ahras', 'Tipaza', 'Mila', 'Aïn Defla', 'Naama', 'Aïn Témouchent', 'Ghardaïa', 'Relizane'
];

// Translation object (French and Arabic)
const translations = {
  fr: {
    "Registration": "Inscription",
    "Full Name": "Nom complet",
    "Phone Number": "Numéro de téléphone",
    "Password": "Mot de passe",
    "Age": "Âge",
    "Select Wilaya": "Sélectionnez une Wilaya",
    "Patient": "Patient",
    "Healthcare Provider": "Prestataire de santé",
    "Select Type": "Sélectionnez le type",
    "Doctor": "Médecin",
    "Nurse": "Infirmier/Infirmière",
    "Select Specialty": "Sélectionnez une spécialité",
    "Register": "S'inscrire",
    "Login": "Connexion",
    "Don't have an account?": "Vous n'avez pas de compte ?",
    "Invalid credentials or role": "Identifiants ou rôle invalides",
    "Admin": "Administrateur",
    "Patient Dashboard": "Tableau de bord du patient",
    "Send Request": "Envoyer une demande",
    "Request sent!": "Demande envoyée !",
    "Provider Dashboard": "Tableau de bord du prestataire",
    "Availability": "Disponibilité",
    "Notifications": "Notifications",
    "A patient requires your services, Doctor.": "Un patient a besoin de vos services, Docteur.",
    "Accept": "Accepter",
    "Attended Patients": "Patients traités",
    "Close Consultation": "Terminer la consultation",
    "Ranking": "Classement",
    "Rate": "Noter",
    "Submit Rating": "Soumettre la note",
    "Admin Panel": "Panneau d'administration",
    "Pending Provider Applications": "Demandes de prestataires en attente",
    "Actions": "Actions",
    "Approve": "Approuver",
    "Reject": "Rejeter",
    "Patients": "Patients",
    "Address": "Adresse",
    "Delete": "Supprimer",
    "Healthcare Providers": "Prestataires de santé",
    "Type": "Type",
    "Specialty": "Spécialité",
    "Rating": "Note",
    "Not Rated Yet": "Pas encore noté",
    "Patient Request History": "Historique des demandes des patients",
    "Date": "Date",
    "Provider": "Prestataire",
    "Provider History": "Historique des prestataires",
    "Provider Name": "Nom du prestataire",
    "Action": "Action",
    "Details": "Détails",
    "Became Available": "Est devenu disponible",
    "Became Unavailable": "Est devenu indisponible",
    "Accepted Request": "A accepté la demande",
    "Approved": "Approuvé",
    "Rejected": "Rejeté",
    "Cardiology": "Cardiologie",
    "Dermatology": "Dermatologie",
    "